"""correction-loading-history

Revision ID: 0e6f6a3b42ea
Revises: ba44a3246559
Create Date: 2022-05-14 17:44:26.755174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e6f6a3b42ea'
down_revision = 'ba44a3246559'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
