"""added-data-to-database

Revision ID: 8f5297f63a94
Revises: b5d39f39e045
Create Date: 2022-05-14 13:13:33.109238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f5297f63a94'
down_revision = 'b5d39f39e045'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
