"""added-data-form-Internet

Revision ID: ba44a3246559
Revises: 3b07599b5200
Create Date: 2022-05-14 16:10:20.388822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba44a3246559'
down_revision = '3b07599b5200'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
