"""historical-data-added

Revision ID: e3d80ad10365
Revises: 8791efc972fe
Create Date: 2022-05-18 22:55:58.832323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3d80ad10365'
down_revision = '8791efc972fe'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
